### ISSUE TITLE
[Bug]: Repository link in crate metadata goes to the wrong repo

### ISSUE THREAD

**Issue by dcormier** [kkrypt0nn/simple-semaphore#1]
### Describe the bug

From `crates.io`, `docs.rs`, or [similar](https://lib.rs/crates/simple-semaphore), following the link to the repository for the crate goes to `https://github.com/kkrypt0nn/rust-boilerplate` rather than this repo.

### Reproduction steps

For `docs.rs`:
1. Go to [this crates `docs.rs` page](https://docs.rs/simple-semaphore/0.1.0/simple_semaphore/)
2. Click the menu for the crate at the top
3. Click `Repository`
4. Notice that you end up at `https://github.com/kkrypt0nn/rust-boilerplate`

<img width="400" alt="image" src="https://github.com/user-attachments/assets/42854509-fb23-47bf-8328-d67c13cca157">

For `crates.io`:
1. Go to the [this crates `crates.io` page](https://crates.io/crates/simple-semaphore)
2. Click the repository link
4. Notice that you end up at `https://github.com/kkrypt0nn/rust-boilerplate`

<img width="381" alt="image" src="https://github.com/user-attachments/assets/c196175e-149b-4d70-90f6-43c1b8b34254">

### Expected behavior

One would end up at `https://github.com/kkrypt0nn/simple-semaphore`.

### Screenshots

[docs.rs](https://docs.rs/simple-semaphore/0.1.0/simple_semaphore/)

<img width="375" alt="image" src="https://github.com/user-attachments/assets/73ca1d23-b8c1-43f1-b47b-3faf9938bcdf">

[crates.io](https://crates.io/crates/simple-semaphore)

<img width="450" alt="image" src="https://github.com/user-attachments/assets/e6f0b00b-06ea-420b-b2e1-728142f7b525">

### Environment

- Project Version: 0.1.0

**Comment by kkrypt0nn** [comment]
Thanks for the heads up!

Fixed it in the last commit :)
